name: f1_raceops_analytics
version: "1.0.0"
config-version: 2

profile: f1_raceops_analytics

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  f1_raceops_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
